### ISSUE TITLE
CSS snippets en SCSS

### ISSUE THREAD

**Issue by CarlosLongarela** [closemarketing/wp-development-toolbox#5]
https://github.com/closemarketing/wp-development-toolbox/blob/85d5c2d1640f779edb931d3111720eb169659f36/package.json#L30

¿No sería mejor aquí permitir que estos snippets CSS también se ejecutasen en los archivos SCSS con `"language": "css,scss",` ?

No es un error, es sólo una idea, pero no me deja añadirle la etiqueta de *enhacement*.

**Comment by davidperezgar** [comment]
Gracias Carlos, efectivamente, para que se puedan ejecutar en los dos. Me queda la duda si coge varios argumentos.

**Comment by CarlosLongarela** [comment]
En los snippets propios desde el VSC si funcionan, aquí en la extensión no lo sé.

**Comment by davidperezgar** [comment]
Done
