### ISSUE TITLE
PhpStorm compatibility

### ISSUE THREAD

**Issue by sc0ttkclark** [closemarketing/wp-development-toolbox#7]
I wonder if it would be possible to add compatibility with PhpStorm in some way, or add a separate PhpStorm project that pulls data from these definitions.

**Comment by davidperezgar** [comment]
Hello, I'm afraid not as voluntary work. That would be another project. If you need this integration, we could speak about it. Send me a private message.

**Comment by sc0ttkclark** [comment]
PhpStorm has Live Templates, which allows for this exact kind of thing.

See this example: https://gist.github.com/Rarst/183c38c499515b6d8609

There's a fork of that which shows how you can simplify install: https://gist.github.com/pronskiy/e0463181ed5bf1f08cdcccb32af87dc6

But maybe more importantly, there are repos out there that add live templates as a PhpStorm plugin itself, which can be installed from their plugin site.

Anyways, I'd love to see your efforts here brought over there too, because it seems this is super useful for people (including myself).

As an aside, I'll continue working on Pods snippets this month.

**Comment by davidperezgar** [comment]
Yes, but I prefer VS Code where I work. @CarlosLongarela is working with Pods, so He'll for sure make more snippets.
Regards.

**Comment by sc0ttkclark** [comment]
Sounds good, just wasn't sure if ya'll had interest in expanding there. I'll take a look at it one day when I'm not doing 50 other projects :)

**Comment by davidperezgar** [comment]
Ok Scott!
